openapi: 3.2.0
info:
  title: Skilljar Domains > Published Courses > Student Group…
  version: 1.0.0
  description: The Skilljar API provides comprehensive access to our customer education platform, enabling you to programmatically manage courses, users, enrollments, and more.
tags:
- name: Domains > Published Courses > Student Group Prerequisites
paths:
  /v1/domains/{domain_name}/published-courses/{published_course_id}/student-group-prerequisites:
    get:
      operationId: domains_published_courses_student_group_prerequisites_list
      description: List StudentGroup prerequisites for a PublishedCourse.
      parameters:
      - in: path
        name: domain_name
        schema:
          type: string
          pattern: ^[-:\.0-9a-z]+$
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: path
        name: published_course_id
        schema:
          type: string
          pattern: ^[0-9a-z]+$
        required: true
      tags:
      - Domains > Published Courses > Student Group Prerequisites
      security:
      - OrganizationApiKey: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPublishedCourseStudentGroupPrerequisiteList'
          description: ''
      summary: Domains published courses student group prerequisites list
      x-summary-source: derived
    post:
      operationId: domains_published_courses_student_group_prerequisites_create
      description: Adds a StudentGroup prerequisite for a PublishedCourse and returns a `201` response.
      parameters:
      - in: path
        name: domain_name
        schema:
          type: string
          pattern: ^[-:\.0-9a-z]+$
        required: true
      - in: path
        name: published_course_id
        schema:
          type: string
          pattern: ^[0-9a-z]+$
        required: true
      tags:
      - Domains > Published Courses > Student Group Prerequisites
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishedCourseStudentGroupPrerequisiteRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PublishedCourseStudentGroupPrerequisiteRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PublishedCourseStudentGroupPrerequisiteRequest'
        required: true
      security:
      - OrganizationApiKey: []
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishedCourseStudentGroupPrerequisite'
          description: ''
      summary: Domains published courses student group prerequisites create
      x-summary-source: derived
  /v1/domains/{domain_name}/published-courses/{published_course_id}/student-group-prerequisites/{student_group_id}:
    get:
      operationId: domains_published_courses_student_group_prerequisites_retrieve
      description: Retrieve a StudentGroup prerequisite for a PublishedCourse.
      parameters:
      - in: path
        name: domain_name
        schema:
          type: string
          pattern: ^[-:\.0-9a-z]+$
        required: true
      - in: path
        name: published_course_id
        schema:
          type: string
          pattern: ^[0-9a-z]+$
        required: true
      - in: path
        name: student_group_id
        schema:
          type: string
          pattern: ^[0-9a-z]+$
        required: true
      tags:
      - Domains > Published Courses > Student Group Prerequisites
      security:
      - OrganizationApiKey: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishedCourseStudentGroupPrerequisite'
          description: ''
      summary: Domains published courses student group prerequisites retrieve
      x-summary-source: derived
    delete:
      operationId: domains_published_courses_student_group_prerequisites_destroy
      description: Removes a StudentGroup prerequisite for a PublishedCourse and returns a `204` response.
      parameters:
      - in: path
        name: domain_name
        schema:
          type: string
          pattern: ^[-:\.0-9a-z]+$
        required: true
      - in: path
        name: published_course_id
        schema:
          type: string
          pattern: ^[0-9a-z]+$
        required: true
      - in: path
        name: student_group_id
        schema:
          type: string
          pattern: ^[0-9a-z]+$
        required: true
      tags:
      - Domains > Published Courses > Student Group Prerequisites
      security:
      - OrganizationApiKey: []
      - tokenAuth: []
      responses:
        '204':
          description: No response body
      summary: Domains published courses student group prerequisites destroy
      x-summary-source: derived
components:
  schemas:
    StudentGroupSummary:
      type: object
      description: Serializer for student groups for use GroupVisibility serializers
      properties:
        id:
          type: string
        name:
          type: string
          readOnly: true
      required:
      - id
    PublishedCourseStudentGroupPrerequisiteRequest:
      type: object
      description: Serializer for PublishedCourseStudentGroupPrerequisite
      properties:
        student_group:
          $ref: '#/components/schemas/StudentGroupSummaryRequest'
      required:
      - student_group
    PublishedCourseStudentGroupPrerequisite:
      type: object
      description: Serializer for PublishedCourseStudentGroupPrerequisite
      properties:
        student_group:
          $ref: '#/components/schemas/StudentGroupSummary'
      required:
      - student_group
    PaginatedPublishedCourseStudentGroupPrerequisiteList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type:
          - string
          - 'null'
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/PublishedCourseStudentGroupPrerequisite'
    StudentGroupSummaryRequest:
      type: object
      description: Serializer for student groups for use GroupVisibility serializers
      properties:
        id:
          type: string
          minLength: 1
      required:
      - id
  securitySchemes:
    OrganizationApiKey:
      type: http
      scheme: basic
      description: API key authentication using HTTP Basic Auth. Use your API key as the username and leave password empty.
    tokenAuth:
      type: http
      scheme: bearer
