openapi: 3.2.0
info:
  title: Skilljar Users > Plans API
  version: 1.0.0
  description: The Skilljar API provides comprehensive access to our customer education platform, enabling you to programmatically manage courses, users, enrollments, and more.
tags:
- name: Users > Plans
paths:
  /v1/users/{user_id}/plan-enrollments:
    get:
      operationId: users_plan_enrollments_list
      description: 'List plan enrollments for a user.


        Returns a list of plan enrollments and related details for the user.'
      parameters:
      - in: path
        name: user_id
        schema:
          type: string
          pattern: ^[0-9a-z]+$
        required: true
      tags:
      - Users > Plans
      security:
      - OrganizationApiKey: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPlanEnrollments'
          description: ''
      summary: Users plan enrollments list
      x-summary-source: derived
components:
  schemas:
    UserPlanEnrollments:
      type: object
      properties:
        plan_id:
          type: string
          readOnly: true
        domain_name:
          type: string
          readOnly: true
        enrolled_at:
          type: string
          format: date-time
          readOnly: true
        expires_at:
          type: string
          format: date-time
          readOnly: true
        active:
          type: boolean
          readOnly: true
        enrollment_id:
          type: string
        plan:
          allOf:
          - $ref: '#/components/schemas/UserPlanEnrollmentPlan'
          readOnly: true
      required:
      - enrollment_id
    UserPlanEnrollmentPlan:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        title:
          type: string
          readOnly: true
  securitySchemes:
    OrganizationApiKey:
      type: http
      scheme: basic
      description: API key authentication using HTTP Basic Auth. Use your API key as the username and leave password empty.
    tokenAuth:
      type: http
      scheme: bearer
